### ISSUE TITLE
SEGV on reload spam

### ISSUE THREAD

**Issue by Wolframike** [nktr-cp/webserv#24]
```bash
[Session management Test]: The number of accesses is 39 for ClNECAn0NEw27U14i3lekBtxYO2bt6h4
AddressSanitizer:DEADLYSIGNAL
=================================================================
==71294==ERROR: AddressSanitizer: SEGV on unknown address 0x7ff700000000 (pc 0x00010c4ef9e5 bp 0x7ff7b3a5eec0 sp 0x7ff7b3a5ee30 T0)
==71294==The signal is caused by a READ memory access.
    #0 0x10c4ef9e5 in std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, Session>, std::__1::__map_value_compare<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, Session>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, Session>>>::destroy(std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, Session>, void*>*)+0x105 (webserv:x86_64+0x10004f9e5)
    #1 0x10c4ef8d4 in std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, Session>, std::__1::__map_value_compare<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, Session>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, Session>>>::~__tree()+0x54 (webserv:x86_64+0x10004f8d4)
    #2 0x10c4e5f18 in std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, Session>, std::__1::__map_value_compare<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, Session>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, Session>>>::~__tree()+0x48 (webserv:x86_64+0x100045f18)
    #3 0x10c50b3c8 in std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, Session, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, Session>>>::~map[abi:ue170006]()+0x48 (webserv:x86_64+0x10006b3c8)
    #4 0x10c50b378 in std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, Session, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, Session>>>::~map[abi:ue170006]()+0x48 (webserv:x86_64+0x10006b378)
    #5 0x10c50b328 in SessionManager::~SessionManager()+0x48 (webserv:x86_64+0x10006b328)
    #6 0x10c50a9f8 in SessionManager::~SessionManager()+0x48 (webserv:x86_64+0x10006a9f8)
    #7 0x10c50a95c in Server::~Server()+0x4c (webserv:x86_64+0x10006a95c)
    #8 0x10c50aa48 in Server::~Server()+0x48 (webserv:x86_64+0x10006aa48)
    #9 0x10c4a566e in std::__1::allocator<Server>::destroy[abi:ue170006](Server*)+0x6e (webserv:x86_64+0x10000566e)
    #10 0x10c4a55d4 in void std::__1::allocator_traits<std::__1::allocator<Server>>::destroy[abi:ue170006]<Server, void>(std::__1::allocator<Server>&, Server*)+0x24 (webserv:x86_64+0x1000055d4)
    #11 0x10c4a552a in std::__1::vector<Server, std::__1::allocator<Server>>::__base_destruct_at_end[abi:ue170006](Server*)+0x11a (webserv:x86_64+0x10000552a)
    #12 0x10c4a5004 in std::__1::vector<Server, std::__1::allocator<Server>>::__clear[abi:ue170006]()+0x74 (webserv:x86_64+0x100005004)
    #13 0x10c4a4cbf in std::__1::vector<Server, std::__1::allocator<Server>>::__destroy_vector::operator()[abi:ue170006]()+0x13f (webserv:x86_64+0x100004cbf)
    #14 0x10c4a4aa8 in std::__1::vector<Server, std::__1::allocator<Server>>::~vector[abi:ue170006]()+0x148 (webserv:x86_64+0x100004aa8)
    #15 0x10c4a2398 in std::__1::vector<Server, std::__1::allocator<Server>>::~vector[abi:ue170006]()+0x48 (webserv:x86_64+0x100002398)
    #16 0x10c4a223c in Webserv::~Webserv()+0x6c (webserv:x86_64+0x10000223c)
    #17 0x10c4a21b8 in Webserv::~Webserv()+0x48 (webserv:x86_64+0x1000021b8)
    #18 0x10c4a1617 in main+0x537 (webserv:x86_64+0x100001617)
    #19 0x7ff802278365 in start+0x795 (dyld:x86_64+0xfffffffffff5c365)

==71294==Register values:
rax = 0x00007ff700000000  rbx = 0x00007ff7b3a5f180  rcx = 0x0000100000000000  rdx = 0x0000607000000148
rdi = 0x0000607000000130  rsi = 0x00007ff700000000  rbp = 0x00007ff7b3a5eec0  rsp = 0x00007ff7b3a5ee30
 r8 = 0x0000000000000200   r9 = 0x00007fffffffffff  r10 = 0x00007fffffffffff  r11 = 0x00000fffffffffff
r12 = 0x00007ff7b3a5f510  r13 = 0x0000000000000000  r14 = 0x000000010c4a10e0  r15 = 0x00007ff7b3a5f690
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (webserv:x86_64+0x10004f9e5) in std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, Session>, std::__1::__map_value_compare<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, Session>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, Session>>>::destroy(std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, Session>, void*>*)+0x105
==71294==ABORTING
[1]    71294 abort      ./webserv config/test.conf
```

**Comment by Wolframike** [comment]
test.conf
```
Error: webserv: recvUndefined error: 0
```

**Comment by Wolframike** [comment]
起きない
